status = ["ci (staging) / Build", "ci (staging) / Lint style", "ci (staging) / Post-Build Step", "ci (staging) / Post-CI job"]
use_squash_merge = true
timeout_sec = 7200
block_labels = ["WIP", "blocked-by-other-PR", "merge-conflict", "awaiting-CI"]
delete_merged_branches = true
update_base_for_deletes = true
cut_body_after = "\n---"
max_batch_size = 16
