on:
  pull_request_target:
    types: [labeled, unlabeled]

# Limit permissions for GITHUB_TOKEN for the entire workflow
permissions:
  contents: read # minimum permissions for actions/checkout & actions/setup-python
  # All other permissions are implicitly 'none'

jobs:
  # When a PR is (un)labelled with awaiting-author or maintainer-merge,
  # add resp. remove the matching emoji reaction from zulip messages.
  set_pr_emoji:
    if: (github.event.label.name == 'awaiting-author' || github.event.label.name == 'maintainer-merge') &&
        github.repository == 'leanprover-community/mathlib4'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout mathlib repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
          ref: master
          sparse-checkout: |
            scripts/zulip_emoji_reactions.py

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install zulip

    - name: Add or remove emoji
      env:
        ZULIP_API_KEY: ${{ secrets.ZULIP_API_KEY }}
        ZULIP_EMAIL: github-mathlib4-bot@leanprover.zulipchat.com
        ZULIP_SITE: https://leanprover.zulipchat.com
        PR_NUMBER: ${{ github.event.number}}
        LABEL_STATUS: ${{ github.event.action }}
        LABEL_NAME: ${{ github.event.label.name }}
        PR_LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}
      run: |
        printf $'Running the python script with:\nPR number: "%s"\nlabel status: "%s"\nlabel: "%s"\nPR labels: "%s"\n' "$PR_NUMBER" "$LABEL_STATUS" "$LABEL" "$PR_LABELS"
        python scripts/zulip_emoji_reactions.py "$ZULIP_API_KEY" "$ZULIP_EMAIL" "$ZULIP_SITE" "$LABEL_STATUS" "$LABEL_NAME" "$PR_NUMBER" "$PR_LABELS"
